### ISSUE TITLE
hi im hoping theres someone out there

### ISSUE THREAD

**Issue by jmartens2** [buzkill420/LaserShark#10]
hi, i was hoping to use this with a ender3 pro melzi board but it keeps asking for e stepper plug left for y2. can you help?

**Comment by buzkill420** [comment]
Sorry pro, this was a pet project for myself that was only tested on a Ramps 1.4... The code is not clean and probably not worth the time trying to get it to work on your board as of yet....thanks for the interest though

**Comment by jmartens2** [comment]
Thanks for the reply. Wish you luck in the future
